[project]
name = "llm-word-generation-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["openai", "nltk"]

[dependency-groups]
dev = [
    "ruff>=0.9.4",
]
